apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math-api
  template:
    metadata:
      labels:
        app: math-api
    spec:
      containers:
      - name: math-api
        image: yourdockerhub/math-api:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: math-api-service
spec:
  selector:
    app: math-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  clusterIP: None  
